version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: containes/django/Dockerfile
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - db
  web:
    image: nginx
    volumes:
        - ./static:/static
        - ./containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf  # ここでdefault.confをマウント
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app
  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: django_sample

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: xxxxxxxxxx@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
    postgres_data:
    pgadmin4_data: